# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := table_test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

table_test: 
	@echo "==== Building table_test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f table_test.make

clean:
	@${MAKE} --no-print-directory -C . -f table_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   table_test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
